# Generated by Django 4.1.1 on 2022-11-09 07:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_billingaddress_order_refund_payment_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
