# Generated by Django 4.1.1 on 2022-11-09 07:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0005_billingaddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
